PREFIX extfn:<http://www.ontotext.com/js#>
INSERT DATA {
    [] <http://www.ontotext.com/js#register> '''
        function replaceAccent(str) {
            var accentMap = {
                'á': 'a', 'é': 'e', 'í': 'i', 'ó': 'o', 'ú': 'u',
                'Á': 'A', 'É': 'E', 'Í': 'I', 'Ó': 'O', 'Ú': 'U',
                'à': 'a', 'è': 'e', 'ì': 'i', 'ò': 'o', 'ù': 'u',
                'À': 'A', 'È': 'E', 'Ì': 'I', 'Ò': 'O', 'Ù': 'U',
                'ä': 'a', 'ë': 'e', 'ï': 'i', 'ö': 'o', 'ü': 'u',
                'Ä': 'A', 'Ë': 'E', 'Ï': 'I', 'Ö': 'O', 'Ü': 'U',
                'â': 'a', 'ê': 'e', 'î': 'i', 'ô': 'o', 'û': 'u',
                'Â': 'A', 'Ê': 'E', 'Î': 'I', 'Ô': 'O', 'Û': 'U',
                'ã': 'a', 'õ': 'o', 'ñ': 'n',
                'Ã': 'A', 'Õ': 'O', 'Ñ': 'N',
                'ç': 'c', 'Ç': 'C'
            };
            return str.split('').map(function(char) {
                return accentMap[char] || char;
            }).join('');
        }
    '''
}