PREFIX extfn:<http://www.ontotext.com/js#>

INSERT DATA {
    [] <http://www.ontotext.com/js#register> '''
        function sortList(str, order, separator) {
            var list = str.split(separator);
            list.sort(function(a, b) {
                if (order === 'asc') {
                    return a.localeCompare(b);
                } else if (order === 'desc') {
                    return b.localeCompare(a);
                } else {
                    throw new Error("Invalid order parameter. Use 'asc' or 'desc'.");
                }
            });
            return list.join(separator);
        }
    '''
}